### ISSUE TITLE
make it build with boost 1.65.1 (archlinux)

### ISSUE THREAD

**Issue by cleanrock** [rlcevg/CircuitAI#68]
If you try to build with boost 1.65.1 i bet you will see:
error: no matching function for call to ‘assertion_failed(...
Fixed by:

```
$ git diff
diff --git a/src/circuit/resource/MetalData.h b/src/circuit/resource/MetalData.h
index e4555cf..08fd432 100644
--- a/src/circuit/resource/MetalData.h
+++ b/src/circuit/resource/MetalData.h
@@ -10,8 +10,7 @@
 
 #include "AIFloat3.h"
 
-#include <boost/geometry/geometries/box.hpp>
-#include <boost/geometry/geometries/point.hpp>
+#include <boost/geometry.hpp>
 #include <boost/geometry/index/rtree.hpp>
 #include <boost/polygon/voronoi.hpp>
 #include <boost/graph/adjacency_list.hpp>

```
Source: https://stackoverflow.com/questions/40188034/failure-with-boost-geometry-correct

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/9af13ac54152181a37ca0b63fabfde60ab75fc24
Thanks!
