### ISSUE TITLE
README should have build instructions!

### ISSUE THREAD

**Issue by Anarchid** [rlcevg/CircuitAI#2]
I failed to figure out how to make it include the AI wrapper headers, so no way to compile. Halp.

**Comment by rlcevg** [comment]
README is docs. And docs are for lobsters! :P

This should work on Linux (and the way i use it in general):
$ git clone https://github.com/spring/spring.git
$ cd spring && git checkout tags/100.0
$ git clone https://github.com/rlcevg/CircuitAI.git AI/Skirmish/CircuitAI
$ cmake . && make CircuitAI -j8
I'm not sure about "make install" and prefer to copy AI files manually into destination (using shell script, see CppTestAI)

**Comment by Anarchid** [comment]
Yeah, it was the "has to be cloned into spring source directory" that escaped me.

**Comment by Anarchid** [comment]
I did the above incantations, but
'''[f=0000000] Error: Fetched AI library CircuitAI-0.7.3 has no handleEvent functionavailable. It is therefore illegal and will not be used.This usually indicates a problem in the used AI Interfacelibrary (-).
[f=0000000] [CrashHandler] Error: Segmentation fault (SIGSEGV) in spring 100.0
[f=0000000] [CrashHandler] Error: Halted Stacktrace for Spring 100.0 using libunwind:
[f=0000000] [CrashHandler] Error: [00]                                            .../spring() [0x9274ff]  log_util_prepareSection
[f=0000000] [CrashHandler] Error: [01]                                            .../spring() [0x9276a4]  log_util_prepareSection
[f=0000000] [CrashHandler] Error: [02]   /lib/x86_64-linux-gnu/libpthread.so.0(+0x10d10) [0x7f0587677d10]  __restore_rt
[f=0000000] Error: [ErrorMessageBox][1] msg="Spring has crashed:
Segmentation fault (SIGSEGV).

A stacktrace has been written to:
  /home/anarchid/.spring/infolog.txt" IsMainThread()=0 fromMain=0
'''
halp. Do i need to compile cpp wrapper or interface? The included C one doesn't seem to do anything except die in horrible agony of pain.

**Comment by rlcevg** [comment]
Hmm, Vagrantfile will solve it all! (jk)
I'll double check instructions (and code in spring that inflicts such strange error).

**Comment by rlcevg** [comment]
Try latest changes, seems abma fixed it (works for me).

**Comment by lumiera** [comment]
Hello. Platform is amd64 GNU/Linux. GCC is
```
gcc version 5.2.1 20151028 (Debian 5.2.1-23)
```

Build of current circuit (05b813c) against spring 100.0 tag (ef05475) works but produces segfault upon match start with an infolog.txt that look like this (100% reproducible):

```

[f=0000000] Loading Skirmish AIs
[f=0000000] [CrashHandler] Error: Segmentation fault (SIGSEGV) in spring 100.0
[f=0000000] [CrashHandler] Error: Halted Stacktrace for Spring 100.0 using libunwind:
[f=0000000] [CrashHandler] Error: This stack trace indicates a problem with a Skirmish AI library.
[f=0000000] [CrashHandler] Error: [00]                                                                 .../spring() [0x9274ff]  log_util_prepareSection
[f=0000000] [CrashHandler] Error: [01]                                                                 .../spring() [0x9276a4]  log_util_prepareSection
[f=0000000] [CrashHandler] Error: [02]                         /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7f40bac308d0]  __restore_rt
[f=0000000] [CrashHandler] Error: [03]   /tmp/buildd/glibc-2.19/string/../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:278  strerror_l
[f=0000000] [CrashHandler] Error: [04]               .../spring/spring-git/AI/Skirmish/CircuitAI/src/circuit/CircuitAI.cpp:353  circuit::CCircuitAI::IsModValid()
[f=0000000] [CrashHandler] Error: [05]               .../spring/spring-git/AI/Skirmish/CircuitAI/src/circuit/CircuitAI.cpp:394  circuit::CCircuitAI::Init(int, SSkirmishAICallback const*)
[f=0000000] [CrashHandler] Error: [06]               .../spring/spring-git/AI/Skirmish/CircuitAI/src/circuit/CircuitAI.cpp:117  circuit::CCircuitAI::HandleGameEvent(int, void const*)
[f=0000000] [CrashHandler] Error: [07]                         .../spring/spring-git/AI/Skirmish/CircuitAI/src/AIExport.cpp:79  handleEvent
[f=0000000] [CrashHandler] Error: [08]                                                                 .../spring() [0x95c73a]  std::_Rb_tree_iterator<std::pair<unsigned int const, int> > std::_Rb_tree<unsigned int, std::p [...]
[f=0000000] [CrashHandler] Error: [09]                                                                 .../spring() [0x955571]  std::_Rb_tree<int, std::pair<int const, int>, std::_Select1st<std::pair<int const, int> >, std [...]
[f=0000000] [CrashHandler] Error: [10]                                                                 .../spring() [0x961df4]  std::_Rb_tree_iterator<std::pair<unsigned int const, int> > std::_Rb_tree<unsigned int, std::p [...]
[f=0000000] [CrashHandler] Error: [11]                                                                 .../spring() [0x93f309]  std::_Rb_tree<std::string, std::string, std::_Identity<std::string>, std::less<std::string>, s [...]
[f=0000000] [CrashHandler] Error: [12]                                                                 .../spring() [0x5a42cb]  std::_List_base<std::string, std::allocator<std::string> >::_M_clear()
[f=0000000] [CrashHandler] Error: [13]                                                                 .../spring() [0x5a98c8]  std::_List_base<std::string, std::allocator<std::string> >::_M_clear()
[f=0000000] [CrashHandler] Error: [14]                                                                 .../spring() [0x5cb6b0]  std::vector<int, std::allocator<int> >::_M_default_append(unsigned long)
[f=0000000] [CrashHandler] Error: [15]                                                                 .../spring() [0x5cbabe]  std::vector<int, std::allocator<int> >::_M_default_append(unsigned long)
[f=0000000] [CrashHandler] Error: [16]                                                                 .../spring() [0x5d3e01]  void std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std:: [...]
[f=0000000] [CrashHandler] Error: [17]                                                                 .../spring() [0x5d4586]  void std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std:: [...]
[f=0000000] [CrashHandler] Error: [18]                                                                 .../spring() [0x8cc0c3]  safe_strcat
[f=0000000] [CrashHandler] Error: [19]                                                                 .../spring() [0x8d37d8]  safe_strcat
[f=0000000] [CrashHandler] Error: [20]                                                                 .../spring() [0x8a819e]  std::_Rb_tree<char const*, char const*, std::_Identity<char const*>, std::less<char const*>, s [...]
[f=0000000] [CrashHandler] Error: [21]                                                                 .../spring() [0x55422a]  ??
[f=0000000] [CrashHandler] Error: [22]                                             /tmp/buildd/glibc-2.19/csu/libc-start.c:321  __libc_start_main
[f=0000000] [CrashHandler] Error: [23]                                                                 .../spring() [0x581b39]  _start
[f=0000000] Error: [ErrorMessageBox][1] msg="Spring has crashed:
Segmentation fault (SIGSEGV).
```

===

Build of current circuit (05b813c) against current spring develop (323ab5a) works but produces segfault upon match start, without backtrace in infolog.

===

Please provide working instructions of building this code, or at least a binary download of amd64 elf. Thank you.

**Comment by rlcevg** [comment]
Hi lumiera.
v0.7.4 tag (7d134c0) is latest stable circuit. Though apparantly stable also have this bug (no nullptr check).
Backtrace indicates that AI kinda working (atleast starting), build successful.

With what game are you trying to run it? It's compatible with Zero-K only (but for some reason game's name is nullptr).

**Comment by lumiera** [comment]
With Zero-K.

**Comment by rlcevg** [comment]
I'll look deeper into the issue.
As a quick workaround you can comment out [mod validation](https://github.com/rlcevg/CircuitAI/blob/7d134c0330b497ffac4c63e158d381351529f0f6/src/circuit/CircuitAI.cpp#L394)

**Comment by lumiera** [comment]
I've checked out the 0.7.4 tag, and built it against spring 100.0 tag.

Zero-K no longer segfaults, but AI dies immediately after start, with this log:

```
[f=0000000] Warning: AI for team 1 (ID: 0) failed handling event with topic 1, error: 102
[f=0000000] Error: Failed to handle init event: AI for team 1, error 102
[f=0000000] Warning: AI for team 2 (ID: 1) failed handling event with topic 1, error: 102
[f=0000000] Error: Failed to handle init event: AI for team 2, error 102
[f=0000000] Warning: AI for team 3 (ID: 2) failed handling event with topic 1, error: 102
[f=0000000] Error: Failed to handle init event: AI for team 3, error 102
[f=0000000] Warning: AI for team 4 (ID: 3) failed handling event with topic 1, error: 102
[f=0000000] Error: Failed to handle init event: AI for team 4, error 102
[f=0000000] Mex Placement Initialised with 49 spots.
[f=0000000] Switching to Free style camera
[f=0000000] Error: [CreateProgramObject] Tried to create "DecalShaderARB" a ARB shader program on hardware w/o support for it!
[f=0000000] Error: [CreateProgramObject] Tried to create "DecalShaderGLSL" a GLSL shader program on hardware w/o support for it!
[f=0000000] Loaded DecalsDrawer: Legacy
[f=0000000] GameID: 9a644c5649463469cdda1cf040c2d64e
[f=0000000] Connection attempt from q2015
[f=0000000]  -> Version: 100.0
[f=0000000] Set UnitIconDist to 0
[f=0000000] Epicmenu: Switching to COFC camera mode
[f=0000000]  -> Connection established (given id 0)
[f=0000000] Skirmish AI "WALL-E" (ID:0), which controlled team 1 is now dead
[f=0000000] [cawidgets.lua] Error: Error in PlayerChanged(): [string "LuaUI/Widgets/gui_chili_deluxeplayerlist.lu..."]:1277: attempt to index field '?' (a nil value)
[f=0000000] [cawidgets.lua] Error: Removed widget: Chili Deluxe Player List - Alpha 2.02
[f=0000000] Skirmish AI "V.I.K.I." (ID:1), which controlled team 2 is now dead
[f=0000000] Skirmish AI "Megatron O'V.I.K.I." (ID:2), which controlled team 3 is now dead
[f=0000000] Skirmish AI "Megatron" (ID:3), which controlled team 4 is now dead
```

**Comment by rlcevg** [comment]
Does issue exist with CircuitAI only other nativeAIs also affected?
So far i assume broken spring setup.
Engine's API function Mod::GetHumanName must not return null by definition.

Ensure that no spring package from distro is installed, if lobby downloads spring then there may be (path?) conflicts.
Ideally each of next command should return 1 line (with similar path):
```
$ sudo find / -name "spring" -executable -type f
/home/bob/.spring/engine/100.0/spring
$ sudo find / -name "libunitsync.so"
/home/bob/.spring/engine/100.0/libunitsync.so
$ sudo find / -name "libAIInterface.so" | grep '/C/0.1/libAIInterface.so'
/home/bob/.spring/engine/100.0/AI/Interfaces/C/0.1/libAIInterface.so
```

Also check [SpringData](https://springrts.com/wiki/Springsettings.cfg#SpringData) param in springsettings.cfg (no clue about that).

**Comment by rlcevg** [comment]
To ensure that it's not lobby's weird arguments try running spring executable from console and select ai+zk from there. If result will be same then i'll try to make static 64bit build (i'm out of guesses).

**Comment by lumiera** [comment]
Same exact result.

I go to weblobby datafolder, and find /engine/100.0/spring executable, then launch it.

I select game: Zero-K v.1.3.11.2
I select some map.
I select AI: Circuit AI 0.7.4

I press "Test Game".

After the match start there is immediately the victory screen with the same log in console as pasted above (1) failed to handle event 2) ai is now dead).

**Comment by lumiera** [comment]
Thank you for releasing a working .so

However the issue still persists. Building (ddda20c) against spring tag 100.0 produces an AI that is immediately dead upon match start.

**Comment by rlcevg** [comment]
Apparantly there is minimum requirements for some components that i didn't expect (like gcc 4.9+ because of [`<regex>`](http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions) but gcc5 should be prefered [`std::list::size`](https://gcc.gnu.org/gcc-5/changes.html).
Tested Ubuntu14.04 + gcc5.2.1 in virtualbox and everything works fine without any code changes (vagrant config is possible).

Anyway those are the steps for guest Ubuntu system:
1) Install [dev-tools](https://springrts.com/wiki/Building_Spring_on_Linux) (though not sure what is required for AI only)
```
$ sudo apt-get install build-essential cmake git
$ sudo apt-get install libglew-dev libsdl2-dev libdevil-dev libopenal-dev \
 libogg-dev libvorbis-dev libfreetype6-dev p7zip-full libxcursor-dev \
 libboost-thread-dev libboost-regex-dev libboost-system-dev \
 libboost-program-options-dev libboost-signals-dev \
 libboost-chrono-dev libboost-filesystem-dev libunwind8-dev
```
2) Install [gcc 5.2.1](http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04)
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-5 g++-5
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
```
3) Build AI
```
$ git clone https://github.com/spring/spring.git
$ cd spring && git checkout tags/100.0
$ git clone https://github.com/rlcevg/CircuitAI.git AI/Skirmish/CircuitAI
$ cmake . && make CircuitAI
```

**Comment by lumiera** [comment]
I've already mentioned that my gcc is 5.2.1 (7th post from top in this issue).

All of the build dependencies were installed by apt-get build-dep spring

One curious thing: the libSkirmishAI.so that I get as a result of make is 34 MB in size. Maybe this is a clue to solving this.

**Comment by rlcevg** [comment]
I have no idea what's wrong with Debian (any clue?). I do use c++11 features much, maybe it can't handle such responsibility.
The issue is about "build instructions", i did provide them and confirmed they work on Arch Linux and Ubuntu14.04.
Also can you compil spring, is built version working (not asking about default AIs as they don't use c++11)?

As solution to all other distributions Vagrantfile will emerge soon.

**Comment by lumiera** [comment]
I would gladly do such a check but I can not compile spring 100.0.

```
rts/Rendering/GlobalRendering.cpp: In member function ‘void CGlobalRendering::PostInit()’:
rts/Rendering/GlobalRendering.cpp:244:17: error: ‘GL_MAX_UNIFORM_BUFFER_BINDINGS’ was not declared in this scope
   glGetIntegerv(GL_MAX_UNIFORM_BUFFER_BINDINGS, &glslMaxUniformBufferBindings);
                 ^
/rts/Rendering/GlobalRendering.cpp:245:17: error: ‘GL_MAX_UNIFORM_BLOCK_SIZE’ was not declared in this scope
   glGetIntegerv(GL_MAX_UNIFORM_BLOCK_SIZE,      &glslMaxUniformBufferSize);
                 ^
rts/builds/legacy/CMakeFiles/engine-legacy.dir/build.make:4286: recipe for target 'rts/builds/legacy/CMakeFiles/engine-legacy.dir/__/__/Rendering/GlobalRendering.cpp.o' failed
make[2]: *** [rts/builds/legacy/CMakeFiles/engine-legacy.dir/__/__/Rendering/GlobalRendering.cpp.o] Error 1
CMakeFiles/Makefile2:3128: recipe for target 'rts/builds/legacy/CMakeFiles/engine-legacy.dir/all' failed
make[1]: *** [rts/builds/legacy/CMakeFiles/engine-legacy.dir/all] Error 2
```

**Comment by rlcevg** [comment]
Interesting, had [same issue](https://springrts.com/phpbb/viewtopic.php?t=32428) some time ago on arch.
But that thread doesn't have meaningful instructions (system update and git clean -d -f -x fixed it).

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/bb66572e83916f13e70dc1008130393696e8e110

**Comment by lumiera** [comment]
I was able to get both spring and circuit ai built from source and working on debian unstable.

1) fixed the above spring build error by git clean -d -f -x
2) "cmake . ; make -j2" in spring toplevel directory
3) copy the libAIInterface.so in AI/Interfaces/C directory to AI/Interfaces/C/data directory to fix "No such file or directory" error
4) copy CircuitAI's libSkirmishAI.so to its data folder to fix another "No such file or directory" error

After this, the game works, and the AI works.

My conclusion from this is that the error discussed in this issue (dead ai upon match start) could be attributed to library version mismatch between what AI is built with and what the weblobby-downloaded spring is built with; Specifically, quite possibly that this is libstdc++ as a result of ongoing transition mentioned earlier.

**Comment by rlcevg** [comment]
Thanks for the info, will add note into readme (troubleshooting).
